### PR TITLE
Remove Vadim Makeev’s quote

### PR DESCRIPTION
**Pull request by pepelsbey**
- It’s outdated
- It looks silly
- As far as I remember I was never asked to be quoted

### CODE REVIEW

**Comment by tadatuta** [comment]
Maybe we can update it? ;)

**Comment by pepelsbey** [comment]
Nah, I don’t feel like endorsing BEM at the moment. What would React community think! ;)

**Comment by pepelsbey** [comment]
:shipit: please

**Comment by vithar** [comment]
In progress

**Comment by vithar** [comment]
In production.

**Pull request merged**
